# Opt, sol, eval comparison
Make sure that eval produces the same result when running an optimised solution vector.

Use `failure-uq/design_point/find_sol.ipynb` to produce opt, eval and sol input files, then run all of them. The iteration variables won't be written out any more (dataframe writing removed from Process), but the constraints will be. This change will be saved as a stash. This allows comparison of constraints at solutions for all 3 running modes.

In [1]:
from pathlib import Path
import pandas as pd
# from process.io.in_dat import InDat

In [ ]:
# data_path = Path.cwd().parent.parent.parent / "failure-uq/design_point"
# opt_path = data_path / "final_sol_vec_opt.csv"
# eval_path = data_path / "final_sol_vec_eval.csv"

# opt_df = pd.read_csv(opt_path)
# eval_df = pd.read_csv(eval_path)
# pd.concat((opt_df, eval_df))

,Unnamed: 0,b_plasma_toroidal_on_axis,rmajor,temp_plasma_electron_vol_avg_kev,nd_plasma_electrons_vol_avg,hfact,dr_cs,q95,dr_bore,j_cs_flat_top_end,f_c_plasma_non_inductive,t_tf_superconductor_quench,dr_tf_nose_case,dx_tf_turn_steel,f_a_tf_turn_cable_copper,c_tf_turn,f_a_cs_turn_steel,f_nd_impurity_electrons(13),dr_tf_wp_with_insulation
0,0,5.009797,8.730641,11.272414,8.384708e+19,0.881401,0.435708,3.0,2.720307,1.984884e+07,0.560701,18.172184,0.233326,0.008,0.90425,90000.0,0.812983,0.000898,0.507222
0,0,5.009797,8.730641,11.272414,8.384708e+19,0.881401,0.435708,3.0,2.720307,1.984884e+07,0.560701,18.172184,0.233326,0.008,0.90425,90000.0,0.812983,0.000898,0.507222

This confirms that both the opt and eval iteration parameter values are the same when writing the mfiles: same solution vector.

Yet, constraint values are quite different.

Compare input files.

In [ ]:
# in_dat_path = data_path / "lt_IN.DAT"
# in_dat = InDat(str(in_dat_path.resolve()))
# in_dat.write_in_dat(str((data_path / "lt_fmt_IN.DAT").resolve()))

Then diff the formatted LT input file and the eval input: only differences should be opt param vector.

## Compare constraints

In [3]:
opt_cons = pd.read_csv("opt_cons.csv", index_col=0)
sol_cons = pd.read_csv("sol_cons.csv", index_col=0)
eval_cons = pd.read_csv("eval_cons.csv", index_col=0)
df = pd.concat((opt_cons, sol_cons, eval_cons))
df.describe()
# df

,Global power balance consistency,Radial build consistency,Fuelling rate,Injection power upper limit,L-H power threshold limit,Net electric power lower limit,Beta upper limit,Peak toroidal field upper limit,CS coil EOF current density limit,CS coil BOP current density limit,...,Dump time set by VV stress,CS Tresca yield criterion,nd_plasma_electron_on_axis > nd_plasma_pedestal_electron,Upper Lim. on Psep * Bt / q A R,TF coil case stress upper limit,TF coil conduit stress upper lim,Density upper limit,Neutron wall load upper limit,Fusion power upper limit,Burn time lower limit
count,3.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000,3.000000e+00,3.000000e+00,...,3.000000,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00
mean,6.674918e-09,1.021757e-08,-6.821439e-09,-5.828453e-09,3.849794e-01,8.587929e-09,3.974245e-01,0.224601,4.561791e-01,3.010349e-01,...,0.619572,4.371081e-11,6.767835e-01,5.031992e-08,4.382245e-10,0.128524,-1.899527e-08,4.318264e-01,2.805332e-01,-2.078307e-08
std,5.775102e-09,0.000000e+00,5.663365e-09,8.289752e-09,1.490354e-07,2.017506e-08,7.739218e-10,0.000000,3.568313e-11,1.665335e-16,...,0.000000,1.922963e-16,6.309559e-08,8.778828e-08,6.331783e-26,0.000000,3.360892e-08,7.820243e-09,9.899320e-09,2.540369e-08
min,6.403766e-12,1.021757e-08,-1.010479e-08,-1.540063e-08,3.849793e-01,-3.065988e-09,3.974245e-01,0.224601,4.561791e-01,3.010349e-01,...,0.619572,4.371070e-11,6.767835e-01,-3.712868e-10,4.382245e-10,0.128524,-5.780350e-08,4.318264e-01,2.805331e-01,-5.011673e-08
25%,5.007635e-09,1.021757e-08,-1.009118e-08,-8.221601e-09,3.849794e-01,-3.060149e-09,3.974245e-01,0.224601,4.561791e-01,3.010349e-01,...,0.619572,4.371070e-11,6.767835e-01,-3.646726e-10,4.382245e-10,0.128524,-2.869733e-08,4.318264e-01,2.805332e-01,-2.811687e-08
50%,1.000887e-08,1.021757e-08,-1.007756e-08,-1.042567e-09,3.849795e-01,-3.054309e-09,3.974245e-01,0.224601,4.561791e-01,3.010349e-01,...,0.619572,4.371070e-11,6.767835e-01,-3.580585e-10,4.382245e-10,0.128524,4.088487e-10,4.318264e-01,2.805332e-01,-6.117005e-09
75%,1.000917e-08,1.021757e-08,-5.179762e-09,-1.042363e-09,3.849795e-01,1.441489e-08,3.974245e-01,0.224601,4.561791e-01,3.010349e-01,...,0.619572,4.371087e-11,6.767835e-01,7.566552e-08,4.382245e-10,0.128524,4.088491e-10,4.318264e-01,2.805332e-01,-6.116239e-09
max,1.000948e-08,1.021757e-08,-2.819677e-10,-1.042159e-09,3.849795e-01,3.188409e-08,3.974245e-01,0.224601,4.561791e-01,3.010349e-01,...,0.619572,4.371103e-11,6.767836e-01,1.516891e-07,4.382245e-10,0.128524,4.088494e-10,4.318264e-01,2.805332e-01,-6.115473e-09